### ISSUE TITLE
IC not displaying sometimes during creation

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#646] opened 2021-04-16 23:44 UTC
**Describe the bug**
When the user resizes the IC preview, and then pans or zooms the screen in such a way that the original bounding box of the IC are no longer on the screen, the entire preview of the IC will stop displaying (that is, the box and in/outputs of the IC itself, the popup window and its mini canvas and title text box still display).

**To Reproduce**
1. Create any collection of components that form a valid IC.
2. Highlight the nodes and choose the "Create IC" option.
3. Expand the size of the IC in some way.
4. Scroll or zoom the screen such that just the very edge of the preview is visible. It will disappear from the canvas before it should.

**Expected behavior**
We would expect the IC to only stop displaying when the _new_ bounding box is not visible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
May be related in some way to issue #645, which seemed to also relate to the original size of the IC before resizing

**Comment by LeonMontealegre** [comment] 2021-11-20 08:25
Duplicate of #470

**Closed by LeonMontealegre** 2021-11-20 08:25 UTC
Labels: Type: Bug, Area: Frontend, D2, P2, S1
