### ISSUE TITLE
Add linting (eslint?)

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#917] opened 2021-11-25 01:00 UTC
**Is your feature request related to a problem? Please describe.**
When submitting a pull request, it is almost guaranteed that there will be some formatting issue that needs changing. Currently, most contributors will submit a pull request, Leon will point out the formatting issues, then the issues are fixed.

**Describe the solution you'd like**
Using something like eslint can not only automate this process, but also allow the linting to be run locally. Codebeat and Codacy kind of serve as linters, but are only easily useable once the pull request is actually made. eslint allows contributors to check for issues in their code before even needing to make a pull request. eslint also works with [Github Actions](https://github.com/marketplace/actions/run-eslint) and [React](https://www.npmjs.com/package/eslint-plugin-react), so it shouldn't be too hard to add to the current CI process.

**Comment by LeonMontealegre** [comment] 2021-11-25 01:18
Kinda a duplicate of #340 but yeah, someone is workin on it rn

**Comment by TGCrystal** [comment] 2021-11-25 01:19
> Kinda a duplicate of #340 but yeah, someone is workin on it rn

Kinda, that one is for adding more linting rules. This issue for adding linting in general.

**Comment by pbabell** [comment] 2021-11-25 17:12
Just for funsies I set up gts locally. (Hi by the way, introduced to this project by @TGCrystal). Uses eslint to follow googles ts style guide. [https://github.com/google/gts](url). Couple things like whitespace and single vs double quotes are different in this project vs what is in the guide but nothing crazy. Some other things would need to be manually changed like unused variables, and using double vs tripple equals, etc.

**Closed** 2022-01-12 15:48 UTC
Labels: Type: Enhancement, D3, P1, Area: DevOps, S2
